# Generated by Django 3.0.7 on 2020-10-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecgdata',
            old_name='data_id',
            new_name='ecg_id',
        ),
    ]
