# Generated by Django 3.0.7 on 2020-10-16 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201016_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
